version: "3"
services:
  route-postgres:
    image: postgres:16-alpine
    container_name: route-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: route
